name: "<EDGE_HOST_IP/edge##>"
metricbeat.modules:
- module: docker
  #Docker module parameters that has to be monitored based on user requirement, example as below
  metricsets: ["cpu","memory","network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
- module: system
  #System module parameters that has to be monitored based on user requirement, example as below
  metricsets: ["cpu","load","memory","network"]
  period: 10s
#processors:
#  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '<Cloud_Public_IP>:9200'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
