version: "3.5"
services:     
    designer:
        image: fogflow/designer:3.2.2
        volumes:
            - ./config.json:/app/config.json
        ports:
            - 8060:8060
            - 1030:1030
        depends_on: 
            - discovery
            - cloud_broker
            - dgraph
        restart: always
            
    discovery:
        image: fogflow/discovery:3.2.2
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8090:8090
        depends_on:
            - dgraph
        restart: always

    master:
        image: fogflow/master:3.2.2
        volumes:
            - ./config.json:/config.json                                   
        links:
            - rabbitmq        
        ports:
            - 1060:1060 
        depends_on: 
            - rabbitmq
            - discovery
            - cloud_broker
            - dgraph     
        restart: always 
        
    cloud_broker:
        image: fogflow/broker:3.2.2
        volumes:
            - ./config.json:/config.json 
        ports:
            - 8070:8070
        depends_on: 
            - discovery
            - dgraph
        restart: always     
                                        
    cloud_worker:
        image: fogflow/worker:3.2.2
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        depends_on: 
            - cloud_broker
            - rabbitmq
        restart: always
                                        
    rabbitmq:
        image: rabbitmq:3
        ports:
            - 5672:5672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass   
        restart: always
        
    nginx: 
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8770:8770
        depends_on: 
            - discovery    
            - cloud_broker
            - designer
        restart: always

    dgraph:                                   
        image: dgraph/standalone
        volumes:
            - ./dgraph:/dgraph           
        ports:
            - 6080:6080
            - 8082:8080
            - 9082:9080
            - 8000:8000
