version: "3"
services:     
    designer:
        image: fogflow/designer:latest
        volumes:
            - ./config.json:/app/config.json
            - ./data/meta:/app/public/data/meta
            - ./data/photo:/app/public/data/photo                                 
        ports:
            - 8080:8080
            - 1030:1030
            - 1090:1090
        depends_on: 
            - discovery
            - cloud_broker
            - rabbitmq
        restart: always
                       
    discovery:
        image: fogflow/discovery:latest
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8090:8090
        restart: always

    master:
        image: fogflow/master:latest
        volumes:
            - ./config.json:/config.json                                   
        links:
            - rabbitmq        
        ports:
            - 1060:1060 
            - 8010:8010             
        depends_on: 
            - rabbitmq
            - discovery
            - cloud_broker     
        restart: always 
        
    cloud_broker:
        image: fogflow/broker:latest
        volumes:
            - ./config.json:/config.json 
        ports:
            - 8070:8070
        depends_on: 
            - discovery
        restart: always     
                                        
    cloud_worker:
        image: fogflow/worker:latest
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        restart: always
                                        
    rabbitmq:
        image: rabbitmq:3.8
        ports:
            - 5672:5672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass   
        restart: always     
                    
    nginx: 
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on: 
        - discovery    
        - cloud_broker
      restart: always           

