#Cloud-broker deployment and service configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  #FogFlow cloud components will be deployed inside fogflow namespace
  namespace: {{ .Values.namespace }} 
  annotations:
    kompose.version: 1.21.0 (992df58d8)
    "helm.sh/hook-weight": "1"
  creationTimestamp: null
  labels:
    io.kompose.service: edge-broker
  name: edge-broker
spec:
  #replicas will make sure that no. of replicaCount mention in values.yaml
  # are running all the time for the deployment
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: edge-broker
  minReadySeconds: 10    
  #strategy tells about How do want to update the pods?
  strategy:
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  # This template field is a regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: edge-broker
    spec:
      containers:
      - image: fogflow/broker:latest
        imagePullPolicy: Always 
        name: edge-broker
        ports:
        - containerPort: 8060
        #readiness and liveness to check pod's Health 
        readinessProbe:
          tcpSocket:
            port: 8060
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8060
          initialDelaySeconds: 15
          periodSeconds: 20
        resources: 
        #CPU and memory limits for cloud-broker deployment 
          limits:
            memory: 3Gi
            cpu: 1 
          requests:
            memory: 2Gi
            cpu: 1 
        volumeMounts:
        - name: config-json
          mountPath: /config.json
          readOnly: true
      restartPolicy: Always
      #serviceAccountName: fogflow-dns 
      volumes:
       - name: config-json
         hostPath:
           path: {{ .Values.configJson.hostPath.path }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    kompose.version: 1.21.0 (992df58d8) 
  creationTimestamp: null
  labels:
    io.kompose.service: edge-broker
  name: edge-broker
spec:
  ports:
  - name: "8060"
    port: 8060
    targetPort: 8060
  selector:
    io.kompose.service: edge-broker
  externalIPs: {{ .Values.Service.spec.externalIPs }}

