version: "3.3"
services:     
    edge_broker:
        image: fogflow/broker:3.2.8
        volumes:
            - ./config.json:/config.json 
        ports:
            - 8060:8060
        restart: always     
                                        
    edge_worker:
        image: fogflow/worker:3.2.8
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        depends_on: 
            - edge_broker
        restart: always
        
        
